### ISSUE TITLE
'NULL' undeclared (first use in this function)

### ISSUE THREAD

**Issue by effemmeffe** [Ludovic-Lesur/max111xx-driver#1]
I get the following error:
'NULL' undeclared (first use in this function)

In my project I include stddef.h that defines NULL, but it is not referenced anywhere in your project.

**Comment by Ludovic-Lesur** [comment]
Hello @effemmeffe 

The `NULL` macro should be defined in the external `types.h` file provided to the driver, as mentioned in the **README**. You may try to include `stddef.h` in this file or define the macro manually.

Please note that all repositories I develop on my page are **only for my personal use** and are **not fully tested**. The architecture and the driver API will not be suitable for all projects.
